################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &PeternakanOrderer
      Name: PeternakanOrdererMSP
      ID: PeternakanOrdererMSP
      MSPDir: crypto-config/peerOrganizations/orderer.peternakan.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('PeternakanOrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('PeternakanOrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('PeternakanOrdererMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('PeternakanOrdererMSP.member')"

      AnchorPeers:

    - &Peternak
      Name: PeternakMSP
      ID: PeternakMSP
      MSPDir: crypto-config/peerOrganizations/peternak.peternakan.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('PeternakMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('PeternakMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('PeternakMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('PeternakMSP.member')"

      AnchorPeers:
          - Host: peer0.peternak.peternakan.com
            Port: 7041

    - &Admin
      Name: AdminMSP
      ID: AdminMSP
      MSPDir: crypto-config/peerOrganizations/admin.peternakan.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('AdminMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('AdminMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('AdminMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('AdminMSP.member')"

      AnchorPeers:
          - Host: peer0.admin.peternakan.com
            Port: 7061

    - &DKPP
      Name: DKPPMSP
      ID: DKPPMSP
      MSPDir: crypto-config/peerOrganizations/dkpp.peternakan.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('DKPPMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('DKPPMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('DKPPMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('DKPPMSP.member')"

      AnchorPeers:
          - Host: peer0.dkpp.peternakan.com
            Port: 7081

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &Peternakan-ordeerer-groupDefaults
    OrdererType: solo
    Addresses:
        - orderer0.peternakan-ordeerer-group.orderer.peternakan.com:7030
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    # Profile used to create Genesis block for group peternakan-ordeerer-group #
    Peternakan-ordeerer-groupGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *Peternakan-ordeerer-groupDefaults
            Organizations:
                - *PeternakanOrderer
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *PeternakanOrderer
                    - *Peternak
                    - *Admin
                    - *DKPP

    # Profile used to create channeltx for ternak-channel #
    TernakChannel:
        <<: *ChannelDefaults
        Orderer:
            <<: *Peternakan-ordeerer-groupDefaults
            Organizations:
                - *PeternakanOrderer
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Peternak
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Peternak
